<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="sreedevi" failures="1" tests="3" name="Default test" time="9.179" errors="0" timestamp="2025-01-17T10:50:56 IST">
  <testcase classname="TestScript.ManageContactText" name="verifyTheUserIsAbleToUpdateTheContactInformation" time="0.009">
    <skipped/>
  </testcase> <!-- verifyTheUserIsAbleToUpdateTheContactInformation -->
  <testcase classname="TestScript.ManageContactText" name="verifyTheUserIsAbleToUpdateTheContactInformation" time="0.002">
    <skipped/>
  </testcase> <!-- verifyTheUserIsAbleToUpdateTheContactInformation -->
  <testcase classname="TestScript.ManageContactText" name="verifyTheUserIsAbleToUpdateTheContactInformation" time="0.001">
    <failure type="java.lang.Error" message="Unresolved compilation problems: 
	retry cannot be resolved to a type
	Class&amp;lt;Retry&amp;gt; cannot be resolved to a type
	The method enterPassword(String) is undefined for the type LoginPage
	The method submitClick() is undefined for the type LoginPage
	ManageContactPage cannot be resolved to a type
	ManageContactPage cannot be resolved to a type
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
retry cannot be resolved to a type
Class<Retry> cannot be resolved to a type
The method enterPassword(String) is undefined for the type LoginPage
The method submitClick() is undefined for the type LoginPage
ManageContactPage cannot be resolved to a type
ManageContactPage cannot be resolved to a type

at TestScript.ManageContactText.verifyTheUserIsAbleToUpdateTheContactInformation(ManageContactText.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyTheUserIsAbleToUpdateTheContactInformation -->
  <testcase classname="TestScript.ManageContactText" name="verifyTheUpdateButtonIsDisplyedSuccessfully" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTheUpdateButtonIsDisplyedSuccessfully -->
</testsuite> <!-- Default test -->
